services:
  db:
    image: docker.io/postgres:latest
    container_name: Product_Order_db
    ports:
      - 2222:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./initialise_database.sql:/docker-entrypoint-initdb.d/initialise_database.sql
  adminer:
    image: docker.io/adminer
    container_name: testing
    restart: always
    ports:
      - 8081:8080
