services:
  db:
    image: docker.io/postgres:latest
    container_name: transactions-postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./config/initialise_database.sql:/docker-entrypoint-initdb.d/initialise_database.sql
  adminer:
    image: docker.io/adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080